1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [1]:
import numpy as np

A = np.arange(1, 11)        
reshaped = A.reshape(2, 5)  
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2.Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. 

In [5]:
A = np.arange(1,21)  
print(A[5:16] )

[ 6  7  8  9 10 11 12 13 14 15 16]


3.Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4

In [7]:
import pandas as pd

data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)
series['pears'] = 4  
print( series)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


4.Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 

In [11]:
data = {
    'name': ['Alice', 'Anu', 'Charlie', 'David', 'Nithy', 'Franklin', 'Grace', 'Nimmy', 'Nila', 'Janu'],
    'age': [25, 30, 22, 35, 28, 40, 27, 31, 29, 26],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
        name  age gender
0     Alice   25      F
1       Anu   30      M
2   Charlie   22      M
3     David   35      M
4     Nithy   28      F
5  Franklin   40      M
6     Grace   27      F
7     Nimmy   31      F
8      Nila   29      M
9      Janu   26      F


5.Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [13]:
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("DataFrame with Occupation:\n", df)

DataFrame with Occupation:
        name  age gender  occupation
0     Alice   25      F  Programmer
1       Anu   30      M     Manager
2   Charlie   22      M     Analyst
3     David   35      M  Programmer
4     Nithy   28      F     Manager
5  Franklin   40      M     Analyst
6     Grace   27      F  Programmer
7     Nimmy   31      F     Manager
8      Nila   29      M     Analyst
9      Janu   26      F  Programmer


6.Select the rows of the dataframe where the age is greater than or equal to 30

In [15]:
age_above_30 = df[df['age'] >= 30]
print("Rows where age >= 30:\n", age_above_30)

Rows where age >= 30:
        name  age gender  occupation
1       Anu   30      M     Manager
3     David   35      M  Programmer
5  Franklin   40      M     Analyst
7     Nimmy   31      F     Manager


7.Convert this dataframe to a csv file and read that csv file, finally display the contents.


In [17]:
# Save to CSV
df.to_csv("people_data.csv", index=False)

# Read from CSV
df_from_csv = pd.read_csv("people_data.csv")
print("DataFrame from CSV:\n", df_from_csv)

DataFrame from CSV:
        name  age gender  occupation
0     Alice   25      F  Programmer
1       Anu   30      M     Manager
2   Charlie   22      M     Analyst
3     David   35      M  Programmer
4     Nithy   28      F     Manager
5  Franklin   40      M     Analyst
6     Grace   27      F  Programmer
7     Nimmy   31      F     Manager
8      Nila   29      M     Analyst
9      Janu   26      F  Programmer
